import type {
  User,
  Company,
  Branch,
  Training,
  Video,
  SOP,
  Recipe,
  Product,
  Announcement,
  Document,
  Badge,
  Category,
  DashboardStats,
} from "@/types";

export const mockCompany: Company = {
  id: "company-1",
  name: "Kupa Coffee",
  logo: "/kupa-logo.png",
  slug: "kupa-coffee",
  status: "active",
  createdAt: "2024-01-01T00:00:00Z",
};

export const mockBranches: Branch[] = [
  { id: "branch-1", name: "Kadıköy Şubesi", companyId: "company-1", status: "active" },
  { id: "branch-2", name: "Beşiktaş Şubesi", companyId: "company-1", status: "active" },
  { id: "branch-3", name: "Nişantaşı Şubesi", companyId: "company-1", status: "active" },
  { id: "branch-4", name: "Bağcılar Şubesi", companyId: "company-1", status: "inactive" },
];

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Kupa Academy",
    username: "admin",
    password: "admin123",
    email: "admin@kupacoffee.com",
    role: "admin",
    companyId: "company-1",
    status: "active",
    badges: [],
    createdAt: "2024-01-15T00:00:00Z",
    lastLoginAt: "2026-06-30T09:00:00Z",
  },
  {
    id: "user-2",
    name: "Zeynep Kaya",
    username: "zeynep.kaya",
    password: "barista123",
    role: "barista",
    companyId: "company-1",
    branchId: "branch-1",
    status: "active",
    badges: [],
    createdAt: "2024-02-01T00:00:00Z",
    lastLoginAt: "2026-06-29T14:30:00Z",
  },
  {
    id: "user-3",
    name: "Mehmet Demir",
    username: "mehmet.demir",
    password: "barista123",
    role: "barista",
    companyId: "company-1",
    branchId: "branch-1",
    department: "Barista",
    position: "Kıdemli Barista",
    status: "active",
    badges: [],
    createdAt: "2024-03-10T00:00:00Z",
    lastLoginAt: "2026-06-30T08:15:00Z",
  },
  {
    id: "user-4",
    name: "Elif Şahin",
    username: "elif.sahin",
    password: "barista123",
    role: "barista",
    companyId: "company-1",
    branchId: "branch-2",
    department: "Servis",
    position: "Kasa Personeli",
    status: "active",
    badges: [],
    createdAt: "2024-04-05T00:00:00Z",
    lastLoginAt: "2026-06-28T11:00:00Z",
  },
];

export const mockCurrentUser: User = mockUsers[0];

export const mockCategories: Category[] = [
  { id: "cat-1", name: "Kahve Yapımı", slug: "kahve-yapimi", type: "training", order: 1, color: "#dc8f27" },
  { id: "cat-2", name: "Müşteri Hizmetleri", slug: "musteri-hizmetleri", type: "training", order: 2, color: "#3b82f6" },
  { id: "cat-3", name: "Hijyen & Güvenlik", slug: "hijyen-guvenlik", type: "training", order: 3, color: "#22c55e" },
  { id: "cat-4", name: "İşletme", slug: "isletme", type: "training", order: 4, color: "#8b5cf6" },
  { id: "cat-5", name: "Sıcak İçecekler", slug: "sicak-icecekler", type: "recipe", order: 1, color: "#ef4444" },
  { id: "cat-6", name: "Soğuk İçecekler", slug: "soguk-icecekler", type: "recipe", order: 2, color: "#06b6d4" },
  { id: "cat-7", name: "Yiyecekler", slug: "yiyecekler", type: "recipe", order: 3, color: "#f59e0b" },
];

export const mockTrainings: Training[] = [
  {
    id: "training-1",
    title: "Espresso Temelleri",
    description: "Espresso çekimi, öğütme ve ekstraksiyonun temel prensipleri",
    coverImage: "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=600",
    categoryId: "cat-1",
    category: mockCategories[0],
    content: [
      { id: "b1", type: "heading1" as any, data: { content: "Espresso Nedir?" } },
      { id: "b2", type: "paragraph" as any, data: { content: "Espresso, ince öğütülmüş kahve üzerinden yüksek basınçlı sıcak su geçirilerek elde edilen yoğun bir kahve içeceğidir. İyi bir espresso, üzerinde 'crema' adı verilen altın-kahverengi köpük tabakası ile servis edilir." } },
      { id: "b3", type: "heading2" as any, data: { content: "İdeal Çekim Parametreleri" } },
      { id: "b4", type: "bullet_list" as any, data: { content: "Su sıcaklığı: 88–93°C\nÇekim süresi: 25–30 saniye\nKahve miktarı: 18–20 gram\nÇıkan miktar: 36–40 ml\nBasınç: 9 bar" } },
      { id: "b5", type: "info" as any, data: { content: "Öğütme kalınlığı espresso kalitesini en çok etkileyen faktördür. Çok ince öğütme aşırı ekstraksiyona, çok kalın öğütme eksik ekstraksiyona neden olur." } },
      { id: "b6", type: "alert" as any, data: { content: "Su sıcaklığı 95°C'yi geçmemeli! Kahve yanar ve acı bir tat oluşur." } },
      { id: "b7", type: "heading2" as any, data: { content: "Adım Adım Espresso Çekimi" } },
      { id: "b8", type: "bullet_list" as any, data: { content: "Portafiltreyi temizle ve kuru olduğundan emin ol\nTartı üzerine koy ve 18-20 gram kahve öğüt\nKahveyi düz bir şekilde doz\nTamper ile 15-20 kg kuvvetle bastır\nMakineye tak ve hemen çekime başla\n25-30 saniyede 36-40 ml al" } },
      { id: "b9", type: "divider" as any, data: { content: "" } },
      { id: "b10", type: "paragraph" as any, data: { content: "Daha fazla bilgi için aşağıdaki eğitim dökümanını inceleyebilirsiniz." } },
      { id: "b11", type: "pdf" as any, data: { content: "https://www.w3.org/WAI/WCAG21/Techniques/pdf/PDF1.pdf" } },
    ],
    status: "published",
    duration: 45,
    order: 1,
    requiredForRoles: ["barista"],
    completions: [],
    tags: ["espresso", "temel", "barista"],
    companyId: "company-1",
    createdBy: "user-1",
    createdAt: "2024-01-20T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
    publishedAt: "2024-01-20T00:00:00Z",
  },
  {
    id: "training-2",
    title: "Müşteri Karşılama & İletişim",
    description: "Mükemmel müşteri deneyimi için iletişim becerileri",
    coverImage: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=600",
    categoryId: "cat-2",
    category: mockCategories[1],
    content: [],
    status: "published",
    duration: 30,
    order: 2,
    requiredForRoles: ["barista"],
    completions: [],
    tags: ["müşteri", "iletişim", "servis"],
    companyId: "company-1",
    createdBy: "user-1",
    createdAt: "2024-02-10T00:00:00Z",
    updatedAt: "2024-05-15T00:00:00Z",
    publishedAt: "2024-02-10T00:00:00Z",
  },
  {
    id: "training-3",
    title: "Gıda Güvenliği & Hijyen",
    description: "HACCP ilkeleri ve hijyen kuralları",
    coverImage: "https://images.unsplash.com/photo-1585237017125-24baf8d7406c?w=600",
    categoryId: "cat-3",
    category: mockCategories[2],
    content: [],
    status: "published",
    duration: 60,
    order: 3,
    requiredForRoles: ["barista", "admin"],
    completions: [],
    tags: ["hijyen", "güvenlik", "HACCP"],
    companyId: "company-1",
    createdBy: "user-1",
    createdAt: "2024-03-05T00:00:00Z",
    updatedAt: "2024-06-10T00:00:00Z",
    publishedAt: "2024-03-05T00:00:00Z",
  },
  {
    id: "training-4",
    title: "Latte Art Teknikleri",
    description: "Süt köpürtme ve latte art çizim teknikleri",
    coverImage: "https://images.unsplash.com/photo-1541167760496-1628856ab772?w=600",
    categoryId: "cat-1",
    category: mockCategories[0],
    content: [],
    status: "draft",
    duration: 90,
    order: 4,
    requiredForRoles: ["barista"],
    completions: [],
    tags: ["latte art", "süt", "barista"],
    companyId: "company-1",
    createdBy: "user-1",
    createdAt: "2026-06-01T00:00:00Z",
    updatedAt: "2026-06-15T00:00:00Z",
  },
];

export const mockVideos: Video[] = [
  {
    id: "video-1",
    title: "Mükemmel Espresso Çekimi",
    description: "Adım adım espresso çekimi rehberi",
    thumbnail: "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=400",
    youtubeId: "dQw4w9WgXcQ",
    duration: 840,
    categoryId: "cat-1",
    category: mockCategories[0],
    tags: ["espresso", "barista"],
    status: "published",
    views: 245,
    companyId: "company-1",
    createdBy: "user-1",
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-02-01T00:00:00Z",
  },
  {
    id: "video-2",
    title: "Latte Art: Roset Çizimi",
    description: "Profesyonel barista tekniğiyle roset latte art",
    thumbnail: "https://images.unsplash.com/photo-1541167760496-1628856ab772?w=400",
    youtubeId: "dQw4w9WgXcQ",
    duration: 1200,
    categoryId: "cat-1",
    category: mockCategories[0],
    tags: ["latte art", "roset"],
    status: "published",
    views: 189,
    companyId: "company-1",
    createdBy: "user-1",
    createdAt: "2024-03-15T00:00:00Z",
    updatedAt: "2024-03-15T00:00:00Z",
  },
  {
    id: "video-3",
    title: "Yeni Sezon Ürün Tanıtımı",
    description: "2026 Yaz sezonu yeni ürünleri",
    thumbnail: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400",
    youtubeId: "dQw4w9WgXcQ",
    duration: 480,
    categoryId: "cat-7",
    tags: ["sezon", "yeni ürün"],
    status: "published",
    views: 312,
    companyId: "company-1",
    createdBy: "user-1",
    createdAt: "2026-06-01T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
  },
];

export const mockSOPs: SOP[] = [
  {
    id: "sop-1",
    title: "Sabah Açılış Prosedürü",
    description: "Her sabah şube açılışında uygulanacak standart prosedür",
    categoryId: "cat-3",
    steps: [
      { id: "s1", order: 1, title: "Giriş ve güvenlik", description: "Alarm sistemini devre dışı bırakın" },
      { id: "s2", order: 2, title: "Ekipman kontrolü", description: "Espresso makinesi, öğütücü ve buzdolabını kontrol edin" },
      { id: "s3", order: 3, title: "Temizlik", description: "Tezgah ve ekipmanları temizleyin" },
      { id: "s4", order: 4, title: "Stok kontrolü", description: "Günlük stok sayımı yapın" },
    ],
    checklist: [
      { id: "c1", text: "Alarm devre dışı", required: true },
      { id: "c2", text: "Makine ısındı", required: true },
      { id: "c3", text: "Temizlik tamamlandı", required: true },
      { id: "c4", text: "Stok not edildi", required: true },
    ],
    version: "2.1",
    revisionDate: "2026-01-15T00:00:00Z",
    status: "published",
    content: [],
    tags: ["açılış", "rutin"],
    companyId: "company-1",
    createdBy: "user-1",
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "sop-2",
    title: "Kapanış Prosedürü",
    description: "Günlük kapanış rutini",
    categoryId: "cat-3",
    steps: [
      { id: "s1", order: 1, title: "Kasa sayımı", description: "Günlük kasa sayımı yapın" },
      { id: "s2", order: 2, title: "Ekipman temizliği", description: "Tüm ekipmanları temizleyin" },
      { id: "s3", order: 3, title: "Stok güncelleme", description: "Güncel stok durumunu kaydedin" },
    ],
    checklist: [
      { id: "c1", text: "Kasa sayıldı", required: true },
      { id: "c2", text: "Makine temizlendi", required: true },
      { id: "c3", text: "Alarm aktif", required: true },
    ],
    version: "1.3",
    revisionDate: "2025-11-01T00:00:00Z",
    status: "published",
    content: [],
    tags: ["kapanış", "rutin"],
    companyId: "company-1",
    createdBy: "user-1",
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2025-11-01T00:00:00Z",
  },
];

export const mockRecipes: Recipe[] = [
  {
    id: "recipe-1",
    name: "Signature Latte",
    description: "Kupa Coffee'nin özel latte reçetesi",
    categoryId: "cat-5",
    category: mockCategories[4],
    ingredients: [
      { id: "i1", name: "Espresso", amount: 30, unit: "ml" },
      { id: "i2", name: "Tam yağlı süt", amount: 180, unit: "ml" },
      { id: "i3", name: "Vanilyalı şurup", amount: 10, unit: "ml" },
    ],
    preparation: "Espresso çekin, sütü 65°C'ye buharla köpürtün, bardağa döküp latte art yapın.",
    presentation: "Büyük bardak, karamel sos ile servis",
    cupType: "350ml Cam Bardak",
    photo: "https://images.unsplash.com/photo-1541167760496-1628856ab772?w=400",
    allergens: ["süt"],
    cost: 8.50,
    notes: "Sütü aşırı ısıtmayın",
    status: "published",
    content: [],
    tags: ["latte", "signature", "sıcak"],
    companyId: "company-1",
    createdBy: "user-1",
    createdAt: "2024-01-25T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "recipe-2",
    name: "Cold Brew Tonic",
    description: "Yaz sezonunun en serinletici içeceği",
    categoryId: "cat-6",
    category: mockCategories[5],
    ingredients: [
      { id: "i1", name: "Cold brew kahve", amount: 60, unit: "ml" },
      { id: "i2", name: "Tonik suyu", amount: 150, unit: "ml" },
      { id: "i3", name: "Buz", amount: 100, unit: "g" },
      { id: "i4", name: "Limon dilimi", amount: 1, unit: "adet" },
    ],
    preparation: "Bardağa buz doldurun, cold brew ekleyin, üzerine tonik dökün.",
    presentation: "Limon dilimi ve nane ile servis",
    cupType: "400ml Uzun Bardak",
    photo: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400",
    allergens: [],
    cost: 12.00,
    status: "published",
    content: [],
    tags: ["cold brew", "soğuk", "yaz"],
    companyId: "company-1",
    createdBy: "user-1",
    createdAt: "2026-05-01T00:00:00Z",
    updatedAt: "2026-05-01T00:00:00Z",
  },
];

export const mockAnnouncements: Announcement[] = [
  {
    id: "ann-1",
    title: "Yaz Sezonu Yeni Menü Lansmanı",
    content: "1 Temmuz'dan itibaren yeni yaz menümüz tüm şubelerde aktif olacak. Lütfen ürün eğitimlerini tamamlayın.",
    publishDate: "2026-06-28T00:00:00Z",
    targetRoles: ["barista", "admin"],
    targetBranches: [],
    sendNotification: true,
    status: "published",
    priority: "high",
    companyId: "company-1",
    createdBy: "user-1",
    createdAt: "2026-06-28T00:00:00Z",
    updatedAt: "2026-06-28T00:00:00Z",
  },
  {
    id: "ann-2",
    title: "Aylık Değerlendirme Toplantısı",
    content: "Bu ayın değerlendirme toplantısı 5 Temmuz Cumartesi saat 10:00'da yapılacak.",
    publishDate: "2026-06-25T00:00:00Z",
    targetRoles: ["admin"],
    targetBranches: [],
    sendNotification: true,
    status: "published",
    priority: "medium",
    companyId: "company-1",
    createdBy: "user-1",
    createdAt: "2026-06-25T00:00:00Z",
    updatedAt: "2026-06-25T00:00:00Z",
  },
  {
    id: "ann-3",
    title: "Yeni SOP Güncellemeleri",
    content: "Açılış ve kapanış prosedürleri güncellendi. Lütfen yeni versiyonları inceleyin.",
    publishDate: "2026-06-20T00:00:00Z",
    targetRoles: ["barista"],
    targetBranches: [],
    sendNotification: false,
    status: "published",
    priority: "low",
    companyId: "company-1",
    createdBy: "user-1",
    createdAt: "2026-06-20T00:00:00Z",
    updatedAt: "2026-06-20T00:00:00Z",
  },
];

export const mockBadges: Badge[] = [
  {
    id: "badge-1",
    name: "Espresso Ustası",
    icon: "☕",
    description: "Espresso Temelleri eğitimini tamamladı",
    condition: { type: "specific_training", value: "training-1" },
    companyId: "company-1",
  },
  {
    id: "badge-2",
    name: "Güvenlik Uzmanı",
    icon: "🛡️",
    description: "Gıda Güvenliği eğitimini %90+ ile geçti",
    condition: { type: "quiz_score", value: 90 },
    companyId: "company-1",
  },
  {
    id: "badge-3",
    name: "Akademi Mezunu",
    icon: "🎓",
    description: "10 eğitimi başarıyla tamamladı",
    condition: { type: "training_count", value: 10 },
    companyId: "company-1",
  },
  {
    id: "badge-4",
    name: "Sadık Öğrenci",
    icon: "🌟",
    description: "30 gün üst üste giriş yaptı",
    condition: { type: "login_streak", value: 30 },
    companyId: "company-1",
  },
];

export const mockDocumentFolders: import("@/types").DocumentFolder[] = [
  { id: "folder-1", name: "Prosedürler", companyId: "company-1" },
  { id: "folder-2", name: "İnsan Kaynakları", companyId: "company-1" },
  { id: "folder-3", name: "Ürün & Menü", companyId: "company-1" },
  { id: "folder-4", name: "Hijyen & Güvenlik", companyId: "company-1" },
  { id: "folder-5", name: "Eğitim Materyalleri", companyId: "company-1" },
];

export const mockDocuments: import("@/types").Document[] = [
  {
    id: "doc-1",
    name: "Açılış & Kapanış Prosedürleri",
    type: "pdf",
    url: "https://www.w3.org/WAI/WCAG21/Techniques/pdf/PDF1.pdf",
    size: 1200000,
    folderId: "folder-1",
    folder: { id: "folder-1", name: "Prosedürler", companyId: "company-1" },
    tags: ["prosedür", "açılış", "kapanış"],
    status: "published",
    companyId: "company-1",
    createdBy: "user-1",
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2024-01-10T00:00:00Z",
  },
  {
    id: "doc-2",
    name: "Personel El Kitabı",
    type: "pdf",
    url: "https://www.w3.org/WAI/WCAG21/Techniques/pdf/PDF1.pdf",
    size: 3400000,
    folderId: "folder-2",
    folder: { id: "folder-2", name: "İnsan Kaynakları", companyId: "company-1" },
    tags: ["personel", "kurallar", "ik"],
    status: "published",
    companyId: "company-1",
    createdBy: "user-1",
    createdAt: "2024-06-15T00:00:00Z",
    updatedAt: "2024-06-15T00:00:00Z",
  },
  {
    id: "doc-3",
    name: "Kahve Menüsü & Ürün Bilgi Formu",
    type: "pdf",
    url: "https://www.w3.org/WAI/WCAG21/Techniques/pdf/PDF1.pdf",
    size: 950000,
    folderId: "folder-3",
    folder: { id: "folder-3", name: "Ürün & Menü", companyId: "company-1" },
    tags: ["menü", "ürün", "kahve"],
    status: "published",
    companyId: "company-1",
    createdBy: "user-1",
    createdAt: "2026-04-01T00:00:00Z",
    updatedAt: "2026-04-01T00:00:00Z",
  },
  {
    id: "doc-4",
    name: "Hijyen Kuralları & Gıda Güvenliği",
    type: "pdf",
    url: "https://www.w3.org/WAI/WCAG21/Techniques/pdf/PDF1.pdf",
    size: 780000,
    folderId: "folder-4",
    folder: { id: "folder-4", name: "Hijyen & Güvenlik", companyId: "company-1" },
    tags: ["hijyen", "gıda güvenliği", "temizlik"],
    status: "published",
    companyId: "company-1",
    createdBy: "user-1",
    createdAt: "2025-03-20T00:00:00Z",
    updatedAt: "2025-03-20T00:00:00Z",
  },
];

export const mockDashboardStats: DashboardStats = {
  completedTrainings: 2,
  pendingTrainings: 3,
  totalBadges: 1,
  upcomingQuizzes: 2,
  recentAnnouncements: mockAnnouncements.slice(0, 3),
  recentVideos: mockVideos.slice(0, 3),
  trainingProgress: [
    { trainingId: "training-1", title: "Espresso Temelleri", progress: 100, dueDate: undefined },
    { trainingId: "training-2", title: "Müşteri Karşılama", progress: 60 },
    { trainingId: "training-3", title: "Gıda Güvenliği", progress: 0, dueDate: "2026-07-15T00:00:00Z" },
  ],
};
